# fly.toml app configuration file generated for bookworm-server on 2023-10-20T18:09:29+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bookworm-server"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
